FROM node:22-alpine
WORKDIR /app

# cache deps
COPY package*.json ./
RUN npm ci --only=production || npm install --production

# app
COPY . .

ENV NODE_ENV=production
ENV FLAG=flag{fresh_ui_hidden_code}
ENV CODE=opensesame
EXPOSE 80

CMD ["node", "index.js"]
