FROM node:22-alpine
WORKDIR /app

# cache de deps
COPY package*.json ./
RUN npm ci --only=production || npm install --production

# copia app
COPY . .

ENV NODE_ENV=production
# usa os DEFAULTS do código: FLAG e PIN hardcoded acima
EXPOSE 80

CMD ["node", "index.js"]
